apiVersion: v1
kind: Secret
metadata:
  name: heartbeat-config
stringData:
  beat.yml: |-
    heartbeat.monitors:
    - type: tcp
      name: "BayCity FiveM Server"
      schedule: '@every 5s'
      hosts: ["fivem.baycity-roleplay.com:30120"]  
    - type: tcp
      name: "BayCity txAdmin Server"
      schedule: '@every 5s'
      hosts: ["fivem.baycity-roleplay.com:40120"]  
    - type: http
      name: "BayCity Website"
      schedule: '@every 60s'
      hosts: ["https://www.baycity-roleplay.com"]  
    - type: tcp
      name: "WhatPixel FiveM Server"
      schedule: '@every 5s'
      hosts: ["fivem.whatpixelrp.com:30120"]  
    - type: tcp
      name: "WhatPixel txAdmin Server"
      schedule: '@every 5s'
      hosts: ["fivem.whatpixelrp.com:40120"]  
    - type: http
      name: "WhatPixel Website"
      schedule: '@every 60s'
      hosts: ["https://www.whatpixelrp.com"] 
    - type: tcp
      name: "FiveM Auth Services"
      schedule: '@every 5s'
      hosts: ["keymaster.fivem.net:443"]                           
    - type: tcp
      name: "ElasticSearch Cluster"
      schedule: '@every 5s'
      hosts: ["elasticsearch-es-http.default.svc:9200"]
    - type: tcp
      name: "Kibana Server"
      schedule: '@every 5s'
      hosts: ["kibana-kb-http.default.svc:5601"]
    - type: tcp
      name: "Enterprise Search"
      schedule: '@every 5s'
      hosts: ["enterprise-search-ent-http.default.svc:3002"]  
    - type: tcp
      name: "APM Server"
      schedule: '@every 5s'
      hosts: ["apm-server-apm-http.default.svc:8200"] 
    - type: http
      name: "PushingStart Web Server"
      schedule: '@every 5s'
      hosts: ["https://www.pushingstart.com"]                    