apiVersion: v1
kind: Secret
metadata:
  name: heartbeat-config
stringData:
  beat.yml: |-
    heartbeat.monitors:
    - type: tcp
      name: "BayCity FiveM Server"
      schedule: '@every 5s'
      hosts: ["fivem.baycity-roleplay.com:30120"]  
    - type: tcp
      name: "BayCity txAdmin Server"
      schedule: '@every 5s'
      hosts: ["fivem.baycity-roleplay.com:40120"]  
    - type: http
      name: "BayCity Website"
      schedule: '@every 60s'
      hosts: ["https://www.baycity-roleplay.com"]  
    - type: tcp
      name: "FiveM Auth Services"
      schedule: '@every 5s'
      hosts: ["keymaster.fivem.net:443"]                           
    - type: tcp
      name: "ElasticSearch Cluster"
      schedule: '@every 5s'
      hosts: ["elasticsearch-es-http.elastic.svc:9200"]
    - type: tcp
      name: "Kibana Server"
      schedule: '@every 5s'
      hosts: ["kibana-kb-http.elastic.svc:5601"]
    - type: tcp
      name: "Enterprise Search"
      schedule: '@every 5s'
      hosts: ["enterprise-search-ent-http.elastic.svc:3002"]  
    - type: tcp
      name: "APM Server"
      schedule: '@every 5s'
      hosts: ["apm-server-apm-http.elastic.svc:8200"]                   
