apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 1.17.0
  count: 1
  http:
    service:
      spec:
        type: ClusterIP  
  elasticsearchRef:
    name: elasticsearch
  enterpriseSearchRef:
    name: ent-search