apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.17.0
  count: 2
  http:
    service:
      spec:
        type: ClusterIP  
  elasticsearchRef:
    name: elasticsearch
  enterpriseSearchRef:
    name: ent
  config:
     newsfeed.enabled: false    