apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.1.2
  nodeSets:
    - name: master
      count: 1
      config:
        xpack.monitoring.collection.enabled: true
        node:
          roles: [ "master", "remote_cluster_client" ]
          store.allow_mmap: false
    - name: di
      config:
        xpack.monitoring.collection.enabled: true
        node:
          roles: [ "data", "ingest", "transform", "remote_cluster_client" ]
          store.allow_mmap: false
    - name: ml
      config:
        xpack.monitoring.collection.enabled: true
        node:
          roles: [ "ml" ]
          store.allow_mmap: false
