apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  annotations:
    elasticsearch.alpha.elastic.co/autoscaling-spec: |
      {
          "policies": [{
              "name": "di",
              "roles": ["data", "ingest" , "transform", "remote_cluster_client"],
              "deciders": {
                "proactive_storage": {
                    "forecast_window": "5m"
                }
              },
              "resources": {
                  "nodeCount": { "min": 2, "max": 8 },
                  "cpu": { "min": 4, "max": 12 },
                  "memory": { "min": "2Gi", "max": "4Gi" },
                  "storage": { "min": "50Gi", "max": "50Gi" }
              }
          },
          {
              "name": "ml",
              "roles": ["ml", "remote_cluster_client"],
              "deciders": {
                  "ml": {
                      "down_scale_delay": "10m"
                  }
              },
              "resources": {
                  "nodeCount": { "min": 1, "max": 4 },
                  "cpu": { "min": 4, "max": 12 },
                  "memory": { "min": "2Gi", "max": "4Gi" },
                  "storage": { "min": "10Gi", "max": "10Gi" }
              }
          }]
      }
spec:
  version: 8.1.2
  nodeSets:
    - name: master
      count: 1
      config:
        xpack.monitoring.collection.enabled: true
        node:
          roles: [ "master", "remote_cluster_client" ]
          store.allow_mmap: false
    - name: di
      config:
        xpack.monitoring.collection.enabled: true
        node:
          roles: [ "data", "ingest", "transform", "remote_cluster_client" ]
          store.allow_mmap: false
    - name: ml
      config:
        xpack.monitoring.collection.enabled: true
        node:
          roles: [ "ml", "remote_cluster_client"]
          store.allow_mmap: false
