apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana
spec:
  hosts:
  - "apps.pushingstart.com"
  gateways:
  - apps-gateway
  http:
  - match:
    - uri:
        prefix: /kibana
    route:
    - destination:
        port:
          number: 5601
        host: wprp-kibana-kb-http