apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: kibana
spec:
  hostname: apps.pushingstart.com
  acmeProvider:
    authority: none
  tlsSecret:
    name: wprp-kibana-kb-http-ca-internal