apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search 
spec:
  version: 8.1.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config:
    # define the exposed URL at which users will reach Enterprise Search
    ent_search.external_url: https://search.apps.pushingstart.com
    # define the exposed URL at which users will reach Kibana
    kibana.host: https://kibana.apps.pushingstart.com
    # configure app search document size limit
    #app_search.engine.document_size.limit: 100kb
  podTemplate:
    spec:
      containers:
      - name: enterprise-search
        resources:
          requests:
            memory: 2Gi
            cpu: 0.25
          limits:
            memory: 2Gi
            cpu: 0.75
        env:
        - name: JAVA_OPTS
          value: -Xms2048m -Xmx2048m  
    
