apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: kibana
spec:
  hostname: kibana.apps.pushingstart.com
  acmeProvider:
    authority: none
  tlsSecret:
    name: kibana-kb-http-ca-internal
  requestPolicy:
    insecure:
      action: Redirect    