apiVersion: v1
kind: Secret
metadata:
 name: px-vsphere-secret
 namespace: kube-system
type: Opaque
data:
 VSPHERE_USER: YWRtaW5pc3RyYXRvckBwdXNoaW5nc3RhcnQuY29t
 VSPHERE_PASSWORD: Rm9yZG11c3RhbmcxMzEzISEh