apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: wprp-kibana
spec:
  version: 7.17.0
  podTemplate:
    spec:
      containers:
      - name: wprp-kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 4Gi
            cpu: 4  
  count: 1
  http:
    service:
      spec:
        type: ClusterIP  
  elasticsearchRef:
    name: wprp-elastic
  enterpriseSearchRef:
    name: wprp-ent
  config:
     newsfeed.enabled: false
     #server.publicBaseUrl: https://apps.pushingstart.com
     #server.basePath: /kibana