apiVersion: apps/v1
kind: Deployment
replicas: 1
metadata:
  name: paper
  labels:
    app: paper
spec:
  selector:
    matchLabels:
      app: paper
  template:
    metadata:
      labels:
        app: paper
    spec:
      volumes:
        # Declare a Volume called `paper-worlds` that asks `minecraft-data-pvc` for a storage
        - name: paper-worlds
          persistentVolumeClaim:
            claimName: minecraft-data-pvc
      containers:
      - name: paper
        image: git.pushingstart.com:5050/public-repository/wizardly-things/paper:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 1Gi
            cpu: '1'
          limits:
            memory: 8Gi
            cpu: '4'       
        tty: true
        stdin: true
        env:
          - name: eula
            value: "true" # Tells docker-entrypoint.sh to make the eula.txt file
        volumeMounts:
          - name: paper-worlds # Uses paper-worlds Volume to store the data in `/data/worlds` persistently
            mountPath: /data/worlds