apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend
  namespace: default
spec:
  hostname: "apps.pushingstart.com"
  prefix: /backend/
  service: quote
  docs:
    path: "/.ambassador-internal/openapi-docs"