apiVersion: v1
kind: Secret
metadata:
  name: metricbeat-config
stringData:
  - name: ELASTICSEARCH_HOST
    value: ve-eck-elastic
  - name: ELASTICSEARCH_PORT
    value: "9200"
  - name: ELASTICSEARCH_USERNAME
    value: elastic
  - name: ELASTICSEARCH_PASSWORD
    value: E9736fQC76XHw43Mo3h4KpGr