apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev-fivem-deployment
  name: dev-fivem-deployment
  namespace: fivem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-fivem-deployment
  template:
    metadata:
      labels:
        app: dev-fivem-deployment
    spec:
      volumes:
      - name: dev-fivem-data
        persistentVolumeClaim:
          claimName: dev-fivem-data
      - name: dev-fivem-configuration-server-cfg
        configMap:
          name: dev-fivem-configuration
          items:
          - key: server.cfg
            path: server.cfg
      containers:
      - image: registry.apps.pushingstart.com/fivem-dev/baycity:latest
        name: dev-fivem-server
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 4Gi
            cpu: 2
        env:
          - name: SERVER_PROFILE
            value: "default"
          - name: FIVEM_PORT
            value: 30120
          - name: TXADMIN_PORT
            value: 40120
          - name: HOST_UID
            value: 1000
          - name: HOST_GID
            value: 100
          - name: FIVEM_HOSTNAME
            value: "dev-test-001"
          - name: FIVEM_LICENCE_KEY
            value: c4ziazm0kotquctybwy3ay54jkxcem8k
          - name: STEAM_WEBAPIKEY
            value: 149E12A644AF93959C4EB19B34527431
          - name: DATABASE_SERVICE_NAME
            value: 10.5.115.16
          - name: MYSQL_DATABASE
            value: fivem_db
          - name: MYSQL_USER
            value: fivem
          - name: MYSQL_PASSWORD
            value: Fordmustang13!
          - name: TZ
            value: America/Chicago
        ports:
        - containerPort: 30120
          protocol: TCP 
        - containerPort: 30120
          protocol: UDP 
