apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev-fivem-deployment
  name: dev-fivem-deployment
  namespace: fivem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-fivem-deployment
  template:
    metadata:
      labels:
        app: dev-fivem-deployment
    spec:
      volumes:
      - name: dev-fivem-data
        persistentVolumeClaim:
          claimName: dev-fivem-data
      - name: dev-fivem-configuration-server-cfg
        configMap:
          name: dev-fivem-configuration
          items:
          - key: server.cfg
            path: /opt/cfx-server-data/server.cfg
      containers:
      - image: registry.apps.pushingstart.com/fivem-dev/baycity:latest
        name: dev-fivem-server
        resources:
          requests:
            memory: 2Gi
            cpu: 1024m
          limits:
            memory: 4Gi
            cpu: 2048m
        ports:
        - containerPort: 30120
          protocol: TCP 
        - containerPort: 30120
          protocol: UDP 
