kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-fivem-data
  namespace: dev-fivem
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi