apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: emissary-ingress-listener-80
spec:
  port: 80
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF