kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-data-pvc
  namespace: steam-games
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi