apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: steam-games
  labels:
    app: minecraft-server
spec:
  type: LoadBalancer
  ports:
    port: 25565
    protocol: UDP
    targetPort: 25565
  selector:
    app: minecraft-server