---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-6d5e49c7-ee2d-4a9f-b1cc-a72b18b661f8
  namespace: steam-games
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard