---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data-pv
  namespace: steam-games
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard