kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: mssql-data 
  namespace: databases 
spec: 
  accessModes: 
  - ReadWriteOnce 
  storageClassName: standard
  resources: 
    requests: 
      storage: 300Gi 