apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whatpixel-fivem-deployment
  name: whatpixel-fivem-deployment
  namespace: steam-games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatpixel-fivem-deployment
  template:
    metadata:
      labels:
        app: whatpixel-fivem-deployment
    spec:
      volumes:
      - name: whatpixel-fivem-data
        persistentVolumeClaim:
          claimName: whatpixel-fivem-data
      - name: whatpixel-fivem-configuration-server-cfg
        configMap:
          name: whatpixel-fivem-configuration
          items:
          - key: server.cfg
            path: server.cfg
      containers:
      - image: registry.apps.pushingstart.com/whatpixel/fivem:latest
        name: whatpixel-fivem-server
        ports:
        - containerPort: 30120
          protocol: TCP 
        env:
          - name: SRCDS_TOKEN
            valueFrom:
              secretKeyRef:
                name: whatpixel-fivem-token
                key: SRCDS_TOKEN
        volumeMounts:
          - name: whatpixel-fivem-configuration-server-cfg
            mountPath: /home/fivem/fx-server-data/server.cfg
            subPath: server.cfg