kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: whatpixel-fivem-data
  namespace: fivem
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi