apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm
  namespace: default
spec:
  version: 7.17.0
  count: 2
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: apm
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2Gi
            cpu: 2    