apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent
  namespace: logging
subjects:
- kind: ServiceAccount
  name: elastic-agent
roleRef:
  kind: ClusterRole
  name: elastic-agent
  namespace: logging
  apiGroup: rbac.authorization.k8s.io
