apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: default
spec:
  version: 7.15.0
  kibanaRef:
    name: kibana
  elasticsearchRefs:
  - name: elasticsearch
  mode: fleet
  fleetServerEnabled: true
deployment:
  replicas: 1
  podTemplate:
    spec:
      serviceAccountName: fleet-server
      automountServiceAccountToken: true
      securityContext:
        runAsUser: 0
      containers:
      - name: fleet-server
        resources:
          requests:
            memory: 512Mi
            cpu: 1
          limits:
            memory: 1024Mi
            cpu: 2          