apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata: 
  name: fleet-server
spec:
  version: 7.17.0
  kibanaRef:
    name: kibana
  fleetServerRef: 
    name: fleet-server
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: fleet-server
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0