apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
  namespace: ${NAME_SPACE}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      volumes:
      - name: ${APP_NAME}-data
        persistentVolumeClaim:
          claimName: ${APP_NAME}-data
      containers:
      - image: registry.apps.pushingstart.com/microsoft/vsts-agent:latest
        name: ${APP_NAME}-01
        resources:
          requests:
            memory: 1Gi
            cpu: 256m
            ephemeral-storage: "1Gi"
          limits:
            memory: 8Gi
            cpu: 2048m
            ephemeral-storage: "2Gi"
        ports:
        - containerPort: 30120
          protocol: TCP 
        - containerPort: 30120
          protocol: UDP 