kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${APP_NAME}-data
  namespace: ${NAME_SPACE}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi