apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: dev-fivem-baycity
 type: Opaque
 data:
    WSO2_CLOUD_ORG_KEY: "mycompany"
    WSO2_CLOUD_EMAIL: "sample-email@wso2.com"
    WSO2_CLOUD_PASSWORD: "password"
    SERVER_PROFILE: "default"
    FIVEM_PORT: "30120"
    TXADMIN_PORT: "40120"
    HOST_UID: "1000"
    HOST_GID: "100"
    FIVEM_HOSTNAME: dev-fivem-baycity
    FIVEM_LICENCE_KEY: c4ziazm0kotquctybwy3ay54jkxcem8k
    STEAM_WEBAPIKEY: 149E12A644AF93959C4EB19B34527431
    DATABASE_SERVICE_NAME: localhost
    MYSQL_DATABASE: fivem_db
    MYSQL_USER: fivem
    MYSQL_PASSWORD: Fordmustang13!
    SQL_PASS: 1xa4RTL6VL
    GIT_USERNAME: aewadm
    GIT_PASS: Fordmustang13!
    TZ: America/Chicago
immutable: true