apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: elasticsearch-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: elasticsearch-es-default
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
status:
  observedGeneration: 1
  lastScaleTime: <some-time>
  currentReplicas: 5
  desiredReplicas: 5
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 50
        averageValue: 10